"""Make category_id nullable in Todo

Revision ID: 54bd016e2063
Revises: 7879a9371843
Create Date: 2024-12-17 23:19:44.742652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54bd016e2063'
down_revision = '7879a9371843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
