"""Mô tả thay đổi

Revision ID: 8fd35c620ed9
Revises: aac5120dca8e
Create Date: 2024-12-10 09:54:50.615992

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8fd35c620ed9'
down_revision = 'aac5120dca8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_invite_code'), 'user', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invite_code'), table_name='user')
    op.drop_column('user', 'invite_code')
    # ### end Alembic commands ###
